### ISSUE TITLE
嗨，如果传入的图片支持网络地址就好了

### ISSUE THREAD

**Issue by charlesYun** [lele8446/CJLabelTest#14]

**Comment by lele8446** [comment]
可以的，插入图片改为UIImageView，然后就可以随意控制图片的下载了

**Comment by charlesYun** [comment]
嗯，这样可以是可以，不过我在UITableView cell 上面使用，条数很多时，UIImageView的创建是个问题。都是动态数据




Caoyunxiao


在2019年12月19日 16:01，lele8446<notifications@github.com> 写道：

可以的，插入图片改为UIImageView，然后就可以随意控制图片的下载了

**Comment by lele8446** [comment]
动态cell确实是个问题。但你可以将cell对应的imageView作为属性持有，再拼接到NSAttributedString显示，这样借助TableViewCell的重用机制可以避免重复初始化UIImageView的问题

**Comment by caoyunxiao** [comment]
嗨，我看了这块的代码
是网络地址，但是一定要同步吗？这块能不能异步处理呢，比如说先放占位图，等图片下载好了在更新
Caoyunxiao


在2019年12月19日 16:24，lele8446<notifications@github.com> 写道：

动态cell确实是个问题。但你可以将cell对应的imageView作为属性持有，再拼接到NSAttributedString显示，这样借助TableViewCell的重用机制可以避免重复初始化UIImageView的问题

**Comment by caoyunxiao** [comment]
我仔细看了下代码，是否可以先异步下载图片，待完成后，直接通过insertViewAtAttrString
插入，再把整体的attributedText
替换一次，不知道效果好不好
Caoyunxiao


在2020年04月22日 11:01，chinacgcgcg<chinacgcgcg@163.com> 写道：
嗨，我看了这块的代码
是网络地址，但是一定要同步吗？这块能不能异步处理呢，比如说先放占位图，等图片下载好了在更新
Caoyunxiao


在2019年12月19日 16:24，lele8446<notifications@github.com> 写道：

动态cell确实是个问题。但你可以将cell对应的imageView作为属性持有，再拼接到NSAttributedString显示，这样借助TableViewCell的重用机制可以避免重复初始化UIImageView的问题
