### ISSUE TITLE
可否像微信一样，长按的时候，直接选择全部？

### ISSUE THREAD

**Issue by Ryan0520** [lele8446/CJLabelTest#16]
如题，可以新增一个配置项来控制。

**Comment by caoyunxiao** [comment]
直接改代码吧

**Comment by caoyunxiao** [comment]
实现了吗

**Comment by charlesYun** [comment]
这框架没人维护了吗？

**Comment by Ryan0520** [comment]
> 这框架没人维护了吗？

估计是没有人维护了

**Comment by charlesYun** [comment]
你在用吗？


Caoyunxiao


在2020年06月20日 09:19，CoderRyan<notifications@github.com> 写道：

这框架没人维护了吗？

估计是没有人维护了

**Comment by lele8446** [comment]
> 如题，可以新增一个配置项来控制。

已新增分类CJLabel+UIMenu，请更新4.7.2版本

**Comment by Ryan0520** [comment]
> > 如题，可以新增一个配置项来控制。
> 
> 已新增分类CJLabel+UIMenu，请更新4.7.2版本

👍👍👍
